name: Deploy to Namecheap

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Create deploy.zip
        run: |
          mkdir deploy

          cp -r .next/standalone/* deploy/
          mkdir -p deploy/.next
          cp -r .next/static deploy/.next/
          cp -r public deploy/

          cd deploy
          zip -r ../deploy.zip .

      - name: Upload deploy.zip
        uses: appleboy/scp-action@v0.1.7
        with:
          host: premium268.web-hosting.com
          port: 22
          username: beregulj
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "deploy.zip"
          target: "/home/beregulj/public_html/shopify"